CREATE TABLE IF NOT EXISTS Interaction_Events (
  event_id CHAR(36) PRIMARY KEY,
  subject_id VARCHAR(67) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  request_id CHAR(36) NOT NULL,
  action_id CHAR(36) NOT NULL,
  idempotency_key CHAR(71) NOT NULL,
  catalog_course_code VARCHAR(32) NULL,
  section_id INT UNSIGNED NULL,
  academic_year SMALLINT UNSIGNED NOT NULL,
  semester VARCHAR(8) NOT NULL,
  plan_id VARCHAR(80) NULL,
  variant_id VARCHAR(32) NULL,
  plan_rank INT UNSIGNED NULL,
  course_rank INT UNSIGNED NULL,
  source VARCHAR(32) NULL,
  feedback_reason VARCHAR(16) NULL,
  schema_version SMALLINT UNSIGNED NOT NULL,
  profile_schema_version SMALLINT UNSIGNED NOT NULL,
  model_version VARCHAR(64) NOT NULL,
  recommendation_reason_version VARCHAR(64) NULL,
  exposure_json JSON NULL,
  UNIQUE KEY uq_interaction_idempotency (subject_id, idempotency_key),
  INDEX idx_interaction_subject_time (subject_id, occurred_at),
  INDEX idx_interaction_expiry (expires_at),
  CONSTRAINT fk_interaction_subject
    FOREIGN KEY (subject_id) REFERENCES Privacy_Subject_State(subject_id)
)
