CREATE TABLE `User_Course_History_v1_new` (
  `history_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `catalog_course_code` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `academic_year` smallint unsigned NOT NULL,
  `semester` tinyint unsigned NOT NULL,
  `course_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `score` decimal(5,2) DEFAULT NULL,
  `letter_grade` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `credits` decimal(4,1) NOT NULL,
  `passed` tinyint(1) NOT NULL,
  `requirement_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `general_education_category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `graduation_category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unknown',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`history_id`),
  UNIQUE KEY `uk_user_course_history_attempt` (`user_id`, `catalog_course_code`, `academic_year`, `semester`),
  KEY `idx_course_history_user_term` (`user_id`, `academic_year`, `semester`),
  KEY `idx_course_history_catalog_code` (`catalog_course_code`),
  CONSTRAINT `fk_course_history_v1_user` FOREIGN KEY (`user_id`) REFERENCES `User_Profiles` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_course_history_semester` CHECK (`semester` BETWEEN 1 AND 3),
  CONSTRAINT `chk_course_history_passed` CHECK (`passed` IN (0, 1))
);
